config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  get '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/create-event',  to: 'events#new'
  post '/create-event',  to: 'events#create'
  patch '/create-event',  to: 'events#create'

  resources :users do
    resources :comments
    member do
      get :attending
    end
  end

  resources :events do
    resources :comments
    member do
      get :attendees
    end
  end

  resources :users, only: [:show, :edit]
  resources :events
  resources :attends, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :events, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_attends, class_name: "Attend", foreign_key: "attendee_id", dependent: :destroy
  has_many :attending, through: :active_attends, source: :attended_event
  
  validates :name, presence: true, length: {maximum: 50}
  validates :email, presence: true, length: {maximum: 50}, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: {minimum: 6}, presence: true, on: :create
  validates :password_confirmation, length: {minimum: 6}, on: :create
  validates :password, length: {minimum: 6}, presence: true, on: :update, if: :password_digest_changed?
  validates :password_confirmation, length: {minimum: 6}, on: :update, if: :password_digest_changed?
  before_save :normalize_name
  before_save :downcase_email

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  #Adds user to attend list for event
  def attend(event)
    active_attends.create(attended_event_id: event.id)
  end

  #Removes a user from the attend list for event
  def unattend(event)
    active_attends.find_by(attended_event_id: event.id).destroy
  end

  #Returns true if the current user is attending the event
  def attending?(event)
    attending.include?(event)
  end

  #Returns user's upcoming events
  def upcoming_events
    events.where("date > ?", Time.now)
  end

  #Returns user's past events
  def past_events
    events.where("date < ?", Time.now)
  end

private

  # Downcase email before being saved
  def downcase_email
    self.email = email.downcase
  end

  def normalize_name
    self.name = name.downcase.titleize
  end 

  def blank_password?
    self.password = nil if self.password.blank?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :already_logged_in?, only: [:new, :create]

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		log_in @user
  		redirect_to @user
  	else
  		render :new
  	end
  end

  def show
  	@user = User.find(params[:id])

    if current_user && @user.id == current_user.id
      @display_name = "Your"
      @special = "You're"
    else 
      @display_name = "#{@user.name}'s"
    end 
    
    if params[:timeline] == "#{@display_name} Upcoming Events"
      @title = params[:timeline]
      @events = @user.upcoming_events.paginate(page: params[:page], per_page: 12)
    elsif params[:timeline] == "#{@display_name} Past Events"
      @title = params[:timeline]
      @events = @user.past_events.paginate(page: params[:page], per_page: 12)
    else
      @display_name = "#{@user.name} is" if @display_name == "#{@user.name}'s"
      @special ? @title = "Events #{@special} Attending" : @title = "Events #{@display_name} Attending"
      @events = @user.attending.where("date > ?", Time.now).paginate(page: params[:page], per_page: 12)
      @display_name = "#{@user.name}'s" if @display_name == "#{@user.name} is"
    end
  end

  def edit
    @user = User.find(params[:id])
    authorized?(@user)
  end

  def update
    @user = User.find(params[:id])
    return if authorized?(@user)
    if @user.update(user_params)
      flash[:success] = "Updated Successfully"
      redirect_to @user
    else
      render :edit
    end
  end

private

	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_form.html.erb
<%= form_for(@user, url: url) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>  
      <div class="row">
        <div class="col-lg-4 col-lg-offset-4">
          <%= f.label :name %><br>
          <%= f.text_field :name, class: "form-control" %><br>
        </div>
      </div>  

      <div class="row">
        <div class="col-lg-4 col-lg-offset-4">
          <%= f.label :email %><br>
          <%= f.email_field :email, class: "form-control" %><br>
        </div>
      </div>

      <div class="row">
        <div class="col-lg-4 col-lg-offset-4">
          <%= f.label :password %><br>
          <%= f.password_field :password, class: "form-control" %><br>
        </div>
      </div>

      <div class="row">
        <div class="col-lg-4 col-lg-offset-4">
          <%= f.label :password_confirmation, "Password Confirmation" %><br>
          <%= f.password_field :password_confirmation, class: "form-control" %><br>
        </div>
      </div>

      <%= f.submit button_text, class: "btn btn-primary" %><br><br>
    <% end %>

app/views/users/edit.html.erb
  <% provide(:title, "Edit Account") %>

  <!-- Page Content -->
  <div class="container text-center">
    <div class="row">
      <h3>Edit Account</h3>
      (Leave password fields blank if not changing password)
      <hr>
    </div>
    <%= render "user_form", url: nil , button_text: "Edit Account" %>
  </div>

app/views/users/new.html.erb
  <% provide(:title, "Sign Up") %>

  <!-- Page Content -->
  <div class="container text-center">
    <div class="row">
      <h3>Sign Up</h3>
      (All fields are required)
      <hr>
    </div>
    <%= render "user_form", url: signup_path, button_text: "Sign Up" %>
    <p>Already have an account? <%= link_to "Login Here", login_path %></p>
  </div>

app/views/users/show.html.erb
  <% provide(:title, "#{@display_name} Profile") %>

  <!-- Page Content -->
  <div class="container">
    <div class="row">
      <div class="col-md-9 col-md-offset-3 text-center">
        <h1><%= @display_name  %> Profile</h1>
        <hr>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-md-3 text-center" id="search-sidebar">
        <% if current_user %>
          <% if current_user.id == @user.id %>
            <h4><b>Account</b></h4>
            <div class="list-group">
              <%= link_to "Edit Account", edit_user_path, class: "list-group-item" %>
              <%= link_to "Logout",logout_path, method: "delete", class: "list-group-item" %>
            </div>
          <% end %>
        <% end %>
        <h4><b>Filter Events by Condition</b></h4>
        <div class="list-group">
          <%= form_tag @user, method: :get do %>
            <%= submit_tag "#{@display_name} Upcoming Events", name: "timeline", id: "timeline", class: "list-group-item" %>
            <%= submit_tag "#{@display_name} Past Events", name: "timeline", id: "timeline", class: "list-group-item" %>    
            <% if @special %>
              <%= submit_tag "Events #{@special} Attending", name: "timeline", id: "timeline", class: "list-group-item" %>    
            <% else %>
              <% @display_name = "#{@user.name} is" if @display_name == "#{@user.name}'s" %>
              <%= submit_tag "Events #{@display_name} Attending", name: "timeline", id: "timeline", class: "list-group-item" %>  
              <%  @display_name = "#{@user.name}'s" %>
            <% end %>
          <% end %>

        </div>
      </div>

      <div class="col-md-9 text-center">
        <div class="row">
          <div id="sub-title">
            <h3><%= @title %></h3>
            (<%= page_entries_info(@events) %>)
          </div>
          <hr>
          <%= will_paginate(@events) %><br>
          <% if @events.any? %>
            <%= render @events %>
          <% end %>
          <%= will_paginate(@events) %>
        </div>
      </div>
    </div>
  </div>