config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  get '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/create-event',  to: 'events#new'
  post '/create-event',  to: 'events#create'
  patch '/create-event',  to: 'events#create'

  resources :users do
    resources :comments
    member do
      get :attending
    end
  end

  resources :events do
    resources :comments
    member do
      get :attendees
    end
  end

  resources :users, only: [:show, :edit]
  resources :events
  resources :attends, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
end

app/models/event.rb
class Event < ActiveRecord::Base
  default_scope -> { order(date: :asc) }
  mount_uploader :picture, PictureUploader
  belongs_to :user
  has_many :passive_attends, class_name: "Attend", foreign_key: "attended_event_id", dependent: :destroy
  has_many :attendees, through: :passive_attends, source: :attendee
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: {maximum: 100}
  validates :description, presence: true, length: {maximum: 1000}
  validates :address, presence: true
  validates :category_id, presence: true
  validate  :picture_size
  after_validation :normalize_title
  after_validation :exclude_united_states_text_from_address
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?

  def Event.upcoming()
    Event.all.where("date > ?", Time.now)
  end

  def Event.past
    Event.all.where("date < ?", Time.now)
  end

  def Event.featured(visitor_latitude, visitor_longitude)
    Event.upcoming.near([visitor_latitude, visitor_longitude], 20).limit(6)
  end

  def has_valid_date?
    self.date < Time.now.advance(days: 1) ? false : true
  end

  def Event.search(params)
    params[:category].to_i != 0 ? events = Event.where(category_id: params[:category].to_i ) : events = Event.all
    events = events.where("lower(title) LIKE ? or lower(description) LIKE ?", "%#{params[:search].downcase}%", "%#{params[:search.downcase].downcase}%") if params[:search].present?
    events = events.near(params[:location], 30) if params[:location].present?
    params[:timeline] == "Past Events" ? events.past : events.upcoming
  end

private

  # Validates the size of an uploaded picture.
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end

  def normalize_title
    self.title = title.downcase.titleize
  end

  def exclude_united_states_text_from_address
    self.address = address.gsub!(/(united states)/i, " ").strip!.chomp!(",") if address.downcase.include?("united states")
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]

  def index
    if params[:category]
      @events =  Event.search(params).paginate(page: params[:page], per_page: 12)
    else
      @events =  Event.upcoming.paginate(page: params[:page], per_page: 12)
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)
    @event.category_id = params[:category_id].to_i
    if @event.save && @event.has_valid_date?
      current_user.attend(@event)
      flash[:success] = "Event Created"
      redirect_to @event
    else
      flash.now[:danger] = "Event date must be 1 or more days ahead from now" if !@event.has_valid_date?
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
    @category = Category.find(@event.category_id).name
    @comments = @event.comments
    @comment = Comment.new
    @hash = Gmaps4rails.build_markers(@event) do |event, marker|
      marker.lat event.latitude
      marker.lng event.longitude
    end
  end

  def edit
    @event = Event.find(params[:id])
    authorized?(@event)
  end

  def update
    @event = Event.find(params[:id])
    authorized?(@event)
    @event.category_id = params[:category_id].to_i
    if @event.update(event_params) && @event.has_valid_date?
      flash[:success] = "Event Updated"
      redirect_to @event
    else
      flash.now[:danger] = "Event date must be 1 or more days ahead from now" if !@event.has_valid_date?
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    authorized?(@event)
    @event.destroy
    flash[:success] = "Event Deleted"
    redirect_to current_user
  end

  def attendees
    @event  = Event.find(params[:id])
    @users = @event.attendees.paginate(page: params[:page])
  end

private

  def event_params
    params.require(:event).permit(:title, :description, :date, :category_id, :picture, :address, :latitude, :longitude)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_attend.html.erb
<%= form_for(current_user.active_attends.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :attended_event_id, @event.id %></div>
  <p class="lead center"><%= f.submit "Attend Event", class: "btn btn-primary" %></p>
<% end %>

app/views/events/_event.html.erb
<div class="col-sm-4 col-lg-4 col-md-4" onclick="document.location='<%= event_path(event.id)%>'" style="cursor: pointer;">
            <div class="thumbnail">
              <% if event.picture? %>
                <%= image_tag event.picture.thumb.url, class: "img-responsive", id: "event-thumbnail", alt: event.picture %>
              <% else %>
                <%= image_tag "event-index-default.jpg", alt: "default-image", id: "event-thumbnail" %>
              <% end %>
              <div class="caption">
                <h4 class="wrap"><%= truncate event.title, length: 49 %></h4>
                <p>Created by: <%= link_to event.user.name, event.user %><br>
                <%= event.date.strftime("Date: %a, %b %d %Y") %><br>
                <%= event.date.strftime("Time: %I : %M %p") %><br>
                Category: <a href="/events?utf8=✓&search=&location=&category=<%=event.category_id %>"><%= Category.find(event.category_id).name %></a></p>
              </div>
              <div class="attendees">
                <% if event.date > Time.now %>
                  <p><%= pluralize(event.attendees.count, 'person') %> attending</p>
                <% else %>
                    <p><%= pluralize(event.attendees.count, 'person') %> attended</p>
                <% end %>
              </div>
            </div>
          </div>

app/views/events/_event_form.html.erb
  <% content_for :head do %>
  <%= javascript_include_tag 'google-places.js' %>
  <% end %>

    <%= form_for(@event, url: url, html: { multipart: true }) do |f| %> 
      <%= render "shared/error_messages", object: f.object %>
      <div class="row">
        <div class="col-lg-6 col-lg-offset-3">
          <%= f.label :title, "Title"%><span id="required">*</span>
          <%= f.text_field :title, class: "form-control" %>
          <p class="help-block"></p>
        </div> 
      </div> 

      <div class="row">
        <div class="col-lg-6 col-lg-offset-3">
          <%= f.label :description, "Description" %><span id="required">*</span>
          <%= f.text_area :description, style: "resize: none;", rows: "10", class: "form-control" %>
          <p class="help-block"></p>
        </div>
      </div>

      <div class="row">
        <div class="col-lg-6 col-lg-offset-3">
          <%= f.label :address, "Address / Location" %><span id="required">*</span>
          <%= f.text_field :address, class: "form-control", id: "txtautocomplete" %>
          <p class="help-block"></p>
        </div> 
      </div> 

      <div class="row">
        <div class="col-lg-6 col-lg-offset-3">
          <%= f.label :category_id, "Category" %><span id="required">*</span><br>
          <%= select_tag :category_id, options_for_select(Category.all.map{ |c| [c.name, c.id] }, @event.category_id ), class: "form-control" %>
          <p class="help-block"></p>
        </div>
      </div>

      <div class="row">
        <div class="col-lg-6 col-lg-offset-3">
          <%= f.label :date, "Date" %><span id="required">*</span><br>
          <%= f.datetime_select :date, options = {ampm: true, minute_step: 15, start_year: Date.today.year, end_year: Date.today.year + 5, order: [:month, :day, :year], default: Time.now} %>
          <p class="help-block"></p>
        </div>
      </div>

      <div class="row" style="margin-top: 20px;">
        <div class="col-lg-6 col-lg-offset-3">
          <% if @event.picture? %>
            <label>Current Image:</label>
            <%= image_tag @event.picture.url, class: "img-responsive", style: "height: 350px; margin-left: auto; margin-right: auto;", alt: @event.picture %><br>
             <%= f.label :picture, "Upload a different event header image (Image must be less than 5MB)" %>
          <% else %>
             <%= f.label :picture, "Optional: Upload an event header image (Must be less than 5MB)" %>
          <% end %>
          <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png', class: "btn btn-primary", style: "margin-left: auto; margin-right: auto;" %>
        </div>
      </div>

      <%= f.submit button, class: "btn btn-primary", style: "margin-top: 30px;" %>
    <% end %>

app/views/events/_unattend.html.erb
<%= form_for(current_user.active_attends.find_by(attended_event_id: @event.id), html: { method: :delete }, remote: true) do |f| %>
  <p class="lead" style="text-align:center;"><%= f.submit "Unattend Event", class: "btn btn-primary" %></p>
<% end %>

app/views/events/edit.html.erb
  <% provide(:title, "Edit Event") %> 

  <div class="container text-center">
    <div class="row">
      <h3>Edit Event</h3>
      <hr> 
    </div> 
    <%= render "event_form", url: @event, button: "Edit Event" %>
  </div>

app/views/events/index.html.erb
  <% provide(:title, "All Events") %> 

  <!-- Page Content -->
  <div class="container">
    <div class="row">
      <div class="col-md-3 text-center" id="search-sidebar">
        <h4><b>Search by</b></h4>
        <%= form_tag events_path, method: :get do %>
          <%= label_tag :search, "Name / Description: " %>
          <%= text_field_tag :search, params[:search], placeholder: "Party, Soccer, Concert, etc.", class: "form-control" %>
          <p class="help-block"></p>

          <%= label_tag :location, "Location, Zip Code, City, State:" %>
          <%= text_field_tag :location, params[:location], placeholder: "San Francisco, 90011, etc.", class: "form-control" %>
          <p class="help-block"></p>

          <%= label_tag :category, "Category: " %><br>
          <%= select_tag :category, options_for_select([["All", "0"], ["Arts", "1"], ["Business", "2"], ["Charity", "3"], ["Education", "4"], ["Fashion", "5"], ["Film & Media", "6"], ["Food & Drink", "7"], ["Health", "8"], ["Hobbies", "9"], ["Holiday", "10"], ["Music", "11"], ["Science & Tech", "12"], ["Spirituality", "13"], ["Sports & Fitness", "14"], ["Travel & Outdoor", "15"], ["Other", "16"]], params[:category] ), class: "form-control" %>
          <p class="help-block"></p>

          <%= submit_tag "Search", name: nil, class: "btn btn-primary" %>
          <p class="help-block"></p><br>

          <h4><b>Filter by Timeline</b></h4>
          <div class="list-group">
            <%= submit_tag "Upcoming Events", name: "timeline", id: "timeline", class: "list-group-item", style: "width: 100%" %>
            <%= submit_tag "Past Events", name: "timeline", id: "timeline", class: "list-group-item", style: "width: 100%" %>      
          </div>
        <% end %>

      </div>

      <div class="col-md-9 text-center">
        <div class="row">
          <h3 id="events"><%= params[:timeline] == "Past Events" ? "Past Events" : "Upcoming Events" %></h3>
          <div>(<%= page_entries_info @events %>)</div>
          <hr>
          <%= will_paginate %><br>
          <% if @events.any? %>
            <%= render @events %>
          <% end %>
          <div class="col-md-12 text-center">
            <div class="row">
              <%= will_paginate %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/events/new.html.erb
  <% provide(:title, "Create Event") %> 
  
  <div class="container text-center">
    <div class="row">
      <h3>Create an Event</h3>
      <hr> 
    </div> 
    <%= render "event_form", url: create_event_path, button: "Create Event" %>
  </div>

app/views/events/show.html.erb
  <% provide(:title, @event.title) %> 

  <!-- Page Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <!-- Event Content -->
        <h1 class="center" class="wrap"><%= @event.title %></h1>
        <h5 class="center">Category: <%= @category %></h5>
        <hr>
        <p class="lead center">Created by: <%= link_to @event.user.name, @event.user %></p>
        <p class="lead center"><b>Time:</b> <%= @event.date.strftime("%I : %M %p") %><br><i class="fa fa-calendar"></i><b> Event Date: </b><%= @event.date.strftime("%A, %B %d %Y") %></p>
        <% if @event.picture? %>
          <%= image_tag @event.picture.url, class: "img-responsive", id: "event-show-image", alt: @event.picture %>
        <% else %>
          <%= image_tag "event-show-default.jpg", class: "img-responsive", alt: "default-image" %>
        <% end %><br>
        <p class="lead wrap">Event Description: <%= @event.description %></p><br>
        <% if current_user%>
          <% if current_user.id == @event.user_id %>
            <p class="lead center" ><%= link_to "Edit Event", edit_event_path(@event), class: "btn btn-primary", id: "show-edit-button" %><%= link_to "Delete Event", @event, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-primary" %></p>
          <% elsif @event.date > Time.now %>  
            <div id="attend_form" >
              <% if current_user.attending?(@event) %>
                <%= render "unattend" %>
              <% else %>
                <%= render "attend" %>
              <% end %>
            </div>
          <% else %>
            <p class="center">Event has ended</p>
          <% end %>
        <% else %>  
          <h4 class="lead center" >(Please <%= link_to "Log In", login_path %> or  <%= link_to "Sign Up", signup_path %> to attend and comment on this event)</h4>
        <% end %><br>

        <!-- Attendees -->
        <% if @event.date > Time.now %> 
          <p class="lead center">People attending this event (<span id="attendees"><%= @event.attendees.count %></span>)</p>
        <% else %>
          <p class="lead center" >People that attended this event (<span id="attendees"><%= @event.attendees.count %></span>)</p> 
        <% end %>
        <hr>
        <div id="users_attending" >
          <% @event.attendees.each do |user| %>
            <li style="text-align:center; list-style: none; font-size: 16px;">Name: <%= link_to user.name, user %></li>
          <% end %>
        </div>
        <hr id="separator">

        <!-- Comments -->
        <h3 class="center" id="comment_count">Comments (<%= @event.comments.count %>)</h3>
        <hr>
        <div class="media comment_list" ">
          <%= render @comments %>
        </div>
        <% if current_user %>
          <div class="well">
            <h4>Leave a Comment:</h4>
            <%= render 'comments/form' %>
          </div>
        <% end %>
      </div>

      <!-- Event Sidebar -->
      <div class="col-md-4">
        <!-- Map -->
        <div class="well" id="event-sidebar">
          <p class="lead"><b>Location:</b> <%= @event.address %></p>
          <div id="map"></div>
        </div>
        <!-- <div class="well" id="event-sidebar">
          <h4>Event Search</h4>
          <div class="input-group">
            <input type="text" class="form-control">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">
                <span class="glyphicon glyphicon-search"></span>
              </button>
            </span>
          </div>
        </div> -->

        <!-- Event Categories Well -->
        <!-- <div class="well" id="event-sidebar">
          <h4>Event Categories</h4>
          <div class="row">
            <div class="col-lg-6">
              <ul class="list-unstyled">
                <li><a href="#">Category Name</a>
                </li>
                <li><a href="#">Category Name</a>
                </li>
                <li><a href="#">Category Name</a>
                </li>
                <li><a href="#">Category Name</a>
                </li>
              </ul>
            </div>
            <div class="col-lg-6">
              <ul class="list-unstyled">
                <li><a href="#">Category Name</a>
                </li>
                <li><a href="#">Category Name</a>
                </li>
                <li><a href="#">Category Name</a>
                </li>
                <li><a href="#">Category Name</a>
                </li>
              </ul>
            </div>
          </div>
        </div> -->
      </div>
    </div>
  </div>

  <script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
      markers = handler.addMarkers(<%=raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      handler.getMap().setZoom(15);
    });
  </script>