config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  get '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/create-event',  to: 'events#new'
  post '/create-event',  to: 'events#create'
  patch '/create-event',  to: 'events#create'

  resources :users do
    resources :comments
    member do
      get :attending
    end
  end

  resources :events do
    resources :comments
    member do
      get :attendees
    end
  end

  resources :users, only: [:show, :edit]
  resources :events
  resources :attends, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <%= favicon_link_tag 'favicon.ico' %>

  <title>Eventor | <%= yield(:title) %></title>

  <!-- Meta Tags -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <meta name="Eventor" content="">
  <%= csrf_meta_tags %>
  
  <!-- Application Stylesheets -->
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

  <!-- Application Javascript -->
  <%= javascript_include_tag 'application' %>

  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


  <!-- Google Maps API -->
  <script src="//maps.google.com/maps/api/js?key=AIzaSyBZ7ZhwVIUYWElrUzcGPx9bPUe3-2RhKXU&libraries=places"></script>
  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>

  <!-- Google Fonts -->
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

  <%= yield :head %>
</head>
<body>
  <!-- Nav-Bar -->
  <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
        </button>
        <%= link_to "Eventor", root_path, class: "navbar-brand page-scroll", style: "color: white;" %>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Events", events_path %></li>
          <% if current_user %>
            <li><%= link_to "Create Event", create_event_path %></li>
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Logout", logout_path, method: "delete" %></li>
          <% else %>                
            <li><%= link_to "Sign Up", signup_path %></li>
            <li><%= link_to "Login", login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <%= render "shared/flash_messages" %>

  <%= yield %>

  <!-- Footer -->
  <div class="container">
    <footer>
      <div class="navbar-header" id="copyright">
        Copyright © <a href="http://www.eric-gonzalez.com/" target="blank" >Eric Gonzalez</a>, All Rights Reserved
      </div>
      <ul id="social-links" class="pull-right">
        <li><a href="https://www.facebook.com/EventorWeb/" target="blank"><i class="fa fa-facebook fa-lg"></i> Facebook</a></li> 
        <li><a href="https://github.com/Twinpair/Eventor" target="blank"><i class="fa fa-github fa-lg"></i> Source Code</a></li>            
      </ul>
    </footer>
  </div>

  <%= debug(params) if Rails.env.development? %>
</body>
</html>